//
// Copyright 2008 (C) Moriyoshi Koizumi. All rights reserved.
//
// This software is distributed under the Boost Software License, Version 1.0.
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#ifndef MOZO_PHP_TSRM_MACROS_HPP
#define MOZO_PHP_TSRM_MACROS_HPP

#ifdef ZTS

#define MOZO_PHP_TSRM_MEMBER void*** tsrm_ls
#define MOZO_PHP_TSRM_HANDLE reinterpret_cast<void***>(ts_resource_ex(0, 0))
#define MOZO_PHP_TSRM_DIRECT_C MOZO_PHP_TSRM_HANDLE
#define MOZO_PHP_TSRM_DIRECT_CC , MOZO_PHP_TSRM_HANDLE
#define MOZO_PHP_TSRM_FETCH_IN_CTOR \
    tsrm_ls(MOZO_PHP_TSRM_HANDLE)
#define MOZO_PHP_TSRM_FETCH_IN_CTOR_C \
    , MOZO_PHP_TSRM_FETCH_IN_CTOR
#else /* ZTS */

#define MOZO_PHP_TSRM_MEMBER
#define MOZO_PHP_TSRM_HANDLE
#define MOZO_PHP_TSRM_DIRECT_C
#define MOZO_PHP_TSRM_DIRECT_CC
#define MOZO_PHP_TSRM_FETCH_IN_CTOR
#define MOZO_PHP_TSRM_FETCH_IN_CTOR_C

#endif /* ZTS */

#endif /* MOZO_PHP_TSRM_MACROS_HPP */
