//
// Copyright 2008 (C) Moriyoshi Koizumi. All rights reserved.
//
// This software is distributed under the Boost Software License, Version 1.0.
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
// 
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#include <boost/preprocessor/expand.hpp>

BOOST_PHP_MODULE(
    BOOST_PHP_MODULE_NAME,
    BOOST_PHP_MODULE_VERSION,
    BOOST_PHP_MODULE_CLASS_NAME
)

#define __BOOST_PHP_MODULE_DEF_TMP1 \
    BOOST_PP_EXPAND(BOOST_PP_CAT(COMPILE_DL_, BOOST_PHP_MODULE_CAPITALIZED_NAME))
#if defined(/**/__BOOST_PHP_MODULE_DEF_TMP1)
#define __BOOST_PHP_MODULE_DEF_TMP2(x) \
    ZEND_GET_MODULE(x)
__BOOST_PHP_MODULE_DEF_TMP2(BOOST_PHP_MODULE_NAME)
#endif

#undef BOOST_PHP_MODULE_NAME
#undef BOOST_PHP_MODULE_VERSION
#undef BOOST_PHP_MODULE_CLASS_NAME
